services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Bolius\BoliusZendesk\Service\ZendeskService:

  Bolius\BoliusFormZendesk\Service\ZendeskHandler:
    arguments:
      $zendeskService: '@Bolius\BoliusZendesk\Service\ZendeskService'

  Bolius\BoliusFormZendesk\Domain\Finishers\CustomFinisher:
    arguments:
      $zendeskService: '@Bolius\BoliusZendesk\Service\ZendeskService'